# dev
version: '3.7'

services:
  api:
    container_name: api
    build:
      context: ./
    volumes:
      - ./:/go/src/api/
    ports:
      - "80:80"
  mongo:
    container_name: mongo
    image: mongo
    restart: always
    environment:
        MONGO_INITDB_ROOT_USERNAME: root
        MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - ./mongo_db:/data/db
    ports:
      - "27017:27017"
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
      ME_CONFIG_MONGODB_URL: mongodb://root:password@mongo:27017/
  redis:
    image: redislabs/redismod
    volumes:
      - ./redis_db:/data
    ports:
      - "6379:6379"
  redisinsight:
    image: redislabs/redisinsight:latest
    volumes:
      - ./redis_insight:/db
    ports:
      - '8001:8001'

