apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: mongo
  name: mongo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: mongo
    spec:
      containers:
      - image: mongo
        name: mongo
        command: ["/bin/sh"]
        args: ["-c", "mongod --bind_ip_all"]
        #livenessProbe:
        #  exec:
        #    command:
        #      - mongod
        #  initialDelaySeconds: 30
        #  periodSeconds: 10
        #  timeoutSeconds: 5
        #  successThreshold: 1
        #  failureThreshold: 6
        #readinessProbe:
        #  exec:
        #    command:
        #      - mongod
        #  initialDelaySeconds: 30
        #  periodSeconds: 10
        #  timeoutSeconds: 5
        #  successThreshold: 1
        #  failureThreshold: 6
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          value: adminuser
        - name: MONGO_INITDB_ROOT_PASSWORD
          value: root
        volumeMounts:
        - name: "mongo-data-dir"
          mountPath: "/data/db"
      volumes:
      - name: "mongo-data-dir"
        persistentVolumeClaim:
          claimName: "pvc"