name: Test

on:
  pull_request:
    branches:  
      - "**"

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Mod
      run: go mod vendor

    - name: Build
      run: go build cmd/httpserver/main.go

    - name: Test
      run: go test -v -race ./...
